resources:
  - namespace.yml
  - pvc.yml
  - redis-deployment.yml
  - redis-service.yml
  - web-deployment.yml
  - web-service.yml
  - celery-beat-deployment.yml
  - celery-worker-deployment.yml
  - ingress.yml
