apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-club-website
  namespace: it-club-website
  labels:
    app: it-club-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-club-website
  template:
    metadata:
      labels:
        app: it-club-website
    spec:
      nodeSelector:
        worker: aws
      containers:
        - name: it-club-website
          image: akalmannakarmi/it-club-website:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: it-club-website-secret
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/db
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
