apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitness-spark-ingress
  namespace: fitness-spark
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - fitness-spark-api.akal.com.np
      secretName: fitness-spark-tls
  rules:
    - host: fitness-spark-api.akal.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fitness-spark-service
                port:
                  number: 80
