apiVersion: v1
kind: Service
metadata:
  name: fitness-spark-service
  namespace: fitness-spark
spec:
  selector:
    app: fitness-spark
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
